config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #トップページの設定
  root to: 'tasks#index'
  
  #タスク投稿用
  resources :tasks
  
  #ユーザ登録用
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  
  #ログイン機能用
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  #バリデーション
  validates :status, presence: true , length: {maximum: 10}
  
  #userとの関連付け
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  #保存前に大文字を小文字に変換
  before_save { self.email.downcase! }
  
  #バリデーション(name,emailの検証)
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: { case_sensitive: false }
  
  #パスワード機能(has_secure_password)
  has_secure_password
  
  #tasksとの関連付け
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  #ログインフォーム用
  def new
  end

  #ログイン用
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  #変数email,passwordを持つloginメソッドを定義
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #全アクションでログインを要求
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    if logged_in?
      @tasks = current_user.tasks
    end
  end
  
  def show
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'Task が正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task が投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @task.update(task_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end
  
  private
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  #correct_userの定義
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to login_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #ユーザ登録用フォーム
  def new
    @user = User.new
  end

  #ユーザ登録
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash[:danger] = "ユーザの登録に失敗しました。"
      render :new
    end
  end
  
  private
  #user_paramsの定義
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <!-- アラート機能追加(Bootstrap) -->
  <div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <!--　ヘッダー(ナビゲーションバー)の設定　-->
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand h1" href="/">TaskList</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '新規タスクの投稿', new_task_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <!-- ヘッダー追加 -->
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<div class="text-center">
  <h1>Log in</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(url: login_path, scope: :session, local: true) do |f| %>
    
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Log in', class: 'btn btn-primary btn-block' %>
    <% end %>
    
    <p>New user? <%= link_to 'Sign up now!', signup_path %></p>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <!-- アラート機能 -->
  <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content, 'タスク' %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :status, 'ステータス' %>
    <%= f.text_field :status, class: 'form-control' %>
  </div>
  
  <%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>
  
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1><%= current_user.name %>のタスク一覧</h1>
<% if @tasks.any? %>
  <!-- タスクテーブル -->
  <table class="table tale-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>タスク</th>
        <th>ステータス</th>
    </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.content %></td>
          <td><%= task.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<!-- タスク登録ボタン -->
<%= link_to '新規タスクの登録', new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>タスクの新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>ID: <%= @task.id %> のタスク詳細ページ</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>ID</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to '一覧に戻る', root_url, class: 'btn btn-primary' %>
<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-light' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <!--エラーメッセージの表示 -->
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>